fr-fr.js
As stated in issue #1, the translations should be about the same for other French speaking countries.
=> French translation

uk-ua.js
=> Translated to Ukrainian, spell checked

fr-FR
=> Added fr-FR

hi.js
=> Added Hindi translation

mr.js
Added translation to The Marathi language
=> Added Marathi translation

tl-ph.js
=> Add Tagalog translation

sr-sp.js
Added the Serbian Latin translations.
=> Add Serbian (SR) translations

es-ar.js
This PR resolves partial of #11 , adding 🇦🇷 translations.
=> Add Spanish (AR) translations

nb-no.js
=> nb-no Norwegian

de-DE.js
=> added german translation

en-ca.js
Added en-ca translation and fixed some ponctuation
=> Added en-ca translation

zh-TW.js
Translated to Mandarin(Taiwan)
=> zh-TW Mandarin(Taiwan)

lt-LT.js
Added translations for lithuanian language
=> Add lithuanian translation

App texts/de-de.js
see: https://www.korrekturen.de/nachgefragt/gelikt_geliket_oder_geliked.shtml
=> Spelling error corrected

README.md
Associated Issue: #41 
Added all current merged authors:
- tfrommen 
- zilyck 
- karate
- slimjoeX
- wuelcas 
- cercei 
- juanferrgiraldo 
- Aguardientico 
- Metcoder95
- I-am-me 
- AkdM 
- VivekMolkar 
- Bak-JH 
- m4rx 
- mahval 
- jotkate 
- oskarwojciski 
- OlegFilonchuk 
- vr1e 
- rcjavier 
- molcay 
- igavelyuk 
- linj2015 
- jerry855202 
If there's any I have missed please do tell me.
=> Added All Current Merged Authors

Google Play Texts/de-DE.txt
Closes issue #42 for German language
=> German Translation For Google Play

Google Play Texts/fr.txt
#42 
Added a new file titled "fr.txt" under Google Play Texts containing the translations.
Let me know if there's anything that needs to be changed (eg whitespace issues)!
=> Added french translation to Google Play Texts

App texts/es-PE.js
=> added es-pe translations

App texts/th-TH.js
=> Add Thai translation (th-TH.js)

App texts/cs-CZ.js, Google Play Texts/cs-CZ.txt
=> add cs-CZ translation

App texts/es-VE.js, Google Play Texts/es-VE.txt
I think that there needs to be a discussion between the Spanish speaking community whether it makes more sense to use "acompañamiento" instead of "respaldo" as the translation for the word "backing". Other than that, having a locale individually per country is great, as sometimes each country feels more comfortable with reading things in different ways :)
=> Add Spanish Venezuela translations

App texts/ro-RO.js, Google Play Texts/ro-RO.txt
Thanks for letting me contribute.
=> Add Romanian translation for description and js

App texts/nl-NL.js, Google Play Texts/nl-NL.txt, README.md
=> created and translated the nl-NL files

App texts/ro-ro.js
=> Added ro-ro.js

App texts/af.js
=> Adding af translation
